/*
 PureMVC ExtJS Javascript port by Tony DeFusco <tony.defusco@puremvc.org>
 PureMVC - Copyright(c) 2006-2011 Futurescale, Inc., Some rights reserved.
 Your reuse is governed by the Creative Commons Attribution 3.0 License
 */

Ext.namespace('Puremvc.test');

/**
 * @class Test the PureMVC Notifier class.
 *
 * @see Puremvc.patterns.Notifier
 */
Puremvc.test.NotifierTest = new YUITest.TestCase(
/**
 * @lends Puremvc.test.NotifierTest.prototype
 */
{
  /**
   * The name of the test case - if not provided, one is automatically
   * generated by the YUITest framework.
   *
   * @type {String}
   * @private
   */
  name: "PureMVC Notifier class tests",

  /**
   * Sets up data that is needed by each test.
   */
  setUp: function() {
  },

  /**
   * Cleans up everything that was created by setUp().
   */
  tearDown: function() {
  },

  /**
   * Tests if constructing the Puremvc.patterns.Notifier also create a Puremvc.patterns.Facade instance.
   */
  testConstructor: function() {
    // Create a new subclass of Puremvc.patterns.Notifier and verify that its Puremvc.patterns.Facade
    // has well been created.
    var notifierTestSub/*Puremvc.test.NotifierTestSub*/ = new NotifierTestSub();

    // Test assertions.
    YUITest.Assert.isTrue(
      notifierTestSub.hasFacade(),
      "Expecting notifierTestSub.hasFacade() === true"
      );
  },

  /**
   * Tests sending a Puremvc.patterns.Notification from the Puremvc.patterns.Notifier.
   */
  testSendNotification: function() {
    // Create the Puremvc.patterns.Facade, register the Puremvc.test.FacadeTestCommand to
    // handle 'NotifierTest' notifications.
    var facade/*Puremvc.patterns.Facade*/ = Puremvc.patterns.Facade.getInstance();
    facade.registerCommand('NotifierTestNote', NotifierTestCommand);

    // Send Puremvc.patterns.Notification. The Puremvc.patterns.Command associated with the event
    // (Puremvc.test.NotifierTestCommand) will be invoked, and will multiply
    // the vo.input value by two and set the result on vo.result
    var vo/*Puremvc.test.NotifierTestVO*/ = new NotifierTestVO(32);
    facade.sendNotification('NotifierTestNote', vo);

    // Test assertions.
    YUITest.Assert.areEqual(
      64,
      vo.result,
      "Expecting vo.result == 64"
      );
  }
});

Alias('Puremvc.test.NotifierTest');
