/*
 PureMVC ExtJS Javascript port by Tony DeFusco <tony.defusco@puremvc.org>
 PureMVC - Copyright(c) 2006-2011 Futurescale, Inc., Some rights reserved.
 Your reuse is governed by the Creative Commons Attribution 3.0 License
 */

Ext.namespace('Puremvc.test');

/**
 * @class Test the PureMVC Notification class.
 *
 * @see Puremvc.patterns.Notification
 */
Puremvc.test.NotificationTest = new YUITest.TestCase(
/**
 * @lends Puremvc.test.NotificationTest.prototype
 */
{
  /**
   * The name of the test case - if not provided, one is automatically
   * generated by the YUITest framework.
   *
   * @type {String}
   * @private
   */
  name: "PureMVC Notification class tests",

  /**
   * Sets up data that is needed by each test.
   */
  setUp: function() {
  },

  /**
   * Cleans up everything that was created by setUp().
   */
  tearDown: function() {
  },

  /**
   * Tests setting and getting the name using Puremvc.patterns.Notification class accessor
   * methods.
   */
  testNameAccessors: function() {
    // Create a new Puremvc.patterns.Notification and use accessors to set the note name
    var note/*Puremvc.patterns.Notification*/ = new Puremvc.patterns.Notification('TestNote');

    // Test assertions.
    YUITest.Assert.areEqual(
      'TestNote',
      note.getName(),
      "Expecting note.getName() == 'TestNote'"
      );
  },

  /**
   * Tests setting and getting the body using Puremvc.patterns.Notification class accessor methods.
   */
  testBodyAccessors: function() {
    // Create a new Puremvc.patterns.Notification and use accessors to set the body.
    var note/*Puremvc.patterns.Notification*/ = new Puremvc.patterns.Notification(null);
    note.setBody(5);

    // Test assertions.
    YUITest.Assert.areSame(
      5,
      note.getBody(),
      "Expecting note.getBody() === 5"
      );
  },

  /**
   * Tests setting the name and body using the Puremvc.patterns.Notification class constructor.
   */
  testConstructor: function() {
    // Create a new Puremvc.patterns.Notification using the constructor to set the note name and body.
    var note/*Puremvc.patterns.Notification*/ = new Puremvc.patterns.Notification('TestNote', 5, 'TestNoteType');

    // Test assertions
    YUITest.Assert.areEqual(
      "TestNote",
      note.getName(),
      "Expecting note.getName() == 'TestNote'"
      );

    YUITest.Assert.areSame(
      5,
      note.getBody(),
      "Expecting note.getBody() === 5"
      );

    YUITest.Assert.areEqual(
      "TestNoteType",
      note.getType(),
      "Expecting note.getType() == 'TestNoteType'"
      );
  },

  /**
   * Tests the toString method of the Puremvc.patterns.Notification
   */
  testToString: function() {
    // Create a new Puremvc.patterns.Notification and use accessors to set the notification name.
    var note/*Puremvc.patterns.Notification*/ = new Puremvc.patterns.Notification('TestNote', [1,3,5], 'TestType');
    var ts/*String*/ = "Notification Name: TestNote\nBody:1,3,5\nType:TestType";

    // Test assertions.
    YUITest.Assert.areEqual(
      ts,
      note.toString(),
      "Expecting note.testToString() == '" + ts + "'"
      );
  }
});

Alias('Puremvc.test.NotificationTest');
