/*
 PureMVC ExtJS Javascript port by Tony DeFusco <tony.defusco@puremvc.org>
 PureMVC - Copyright(c) 2006-2011 Futurescale, Inc., Some rights reserved.
 Your reuse is governed by the Creative Commons Attribution 3.0 License
 */

Ext.namespace('Puremvc.test');

/**
 * @class Test the PureMVC Mediator class.
 *
 * @see Puremvc.patterns.Mediator
 */
Puremvc.test.MediatorTest = new YUITest.TestCase(
/**
 * @lends Puremvc.test.MediatorTest.prototype
 */
{
  /**
   * The name of the test case - if not provided, one is automatically
   * generated by the YUITest framework.
   *
   * @type {String}
   * @private
   */
  name: "PureMVC Mediator class tests",

  /**
   * Sets up data that is needed by each test.
   */
  setUp: function() {
  },

  /**
   * Cleans up everything that was created by setUp().
   */
  tearDown: function() {
  },

  /**
   * Tests if constructing the <code>Puremvc.patterns.Mediator</code> also call its super by testing
   * for the existence of its <code>Puremvc.patterns.Notifier</code> superclass Puremvc.patterns.Facade
   * instance.
   */
  testConstructor: function() {
    // Create a new subclass of Puremvc.patterns.Notifier and verify that its Puremvc.patterns.Facade
    // has well been created.
    var mediatorTestSub/*Puremvc.test.MediatorTestSub*/ = new MediatorTestSub();

    // Test assertions
    YUITest.Assert.isTrue(
      mediatorTestSub.hasFacade(),
      "Expecting mediatorTestSub.hasFacade() === true"
      );
  },

  /**
   * Tests getting the name using Puremvc.patterns.Mediator class accessor method.
   */
  testNameAccessor: function() {
    // Create a new Puremvc.patterns.Mediator and use accessors to set its name.
    var mediator/*Puremvc.patterns.Mediator*/ = new Puremvc.patterns.Mediator();

    // Test assertions
    YUITest.Assert.areEqual(
      Puremvc.patterns.Mediator.NAME,
      mediator.getMediatorName(),
      "Expecting mediator.getMediatorName() == Puremvc.patterns.Mediator.NAME"
      );
  },

  /**
   * Tests getting the name using the Puremvc.patterns.Mediator class accessor method.
   */
  testViewAccessor: function() {
    // Create a view object
    var view/*Object*/ = new Object();

    // Create a new Puremvc.patterns.Proxy and use accessors to set its name.
    var mediator/*Puremvc.patterns.Mediator*/ = new Puremvc.patterns.Mediator(Puremvc.patterns.Mediator.NAME, view);

    // Test assertions
    YUITest.Assert.isNotNull(
      mediator.getViewComponent(),
      "Expecting mediator.getViewComponent() !== null"
      );
  }
});

Alias('Puremvc.test.MediatorTest');
